name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9477386
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: false
          packages: |
            platform-tools
            platforms;android-30
            build-tools;30.0.3

      - name: Set up JDK 11 for Build
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          architecture: x64

      - name: Grant execute permission for gradlew
        run: chmod +x MediTime/gradlew

      - name: Build with Gradle
        working-directory: MediTime
        run: ./gradlew build

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: MediTime/app/build/outputs
